name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: npx playwright test --reporter=html
        working-directory: .
        continue-on-error: true

      - name: Debug repo and mytests folder
        run: |
          echo "Root files:"
          ls -la
          echo "-------"
          echo "mytests contents:"
          ls -la mytests
          echo "-------"
          echo "Report folder:"
          ls -la playwright-report || echo "playwright-report not found"

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report/
