name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install
        working-directory: mytests

      - name: Install Playwright Browsers
        run: npx playwright install
        working-directory: mytests

      - name: Run Playwright Tests
        run: npx playwright test --reporter=html
        working-directory: mytests
        continue-on-error: true

      - name: Debug folder contents
        run: ls -R mytests  

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: mytests/playwright-report/
